#! /usr/bin/sh
PIPE_NAME=".pype"
KILL_STRING="KILL_PYPER"
PIPED_SHELL="/bin/python3"
for arg in "$@"
do
    case $arg in 
        -s=*|--shell=*)
            PIPED_SHELL="${arg#*=}"
            ;;
        -k=*|--kill-string=*)
            KILL_STRING="${arg#*=}"
            ;;
        -p=*|-n=*|--pipe-name=*)
            PIPE_NAME="${arg#*=}"
            ;;
    esac
done

mkfifo "$PIPE_NAME"
while [[ -a "$PIPE_NAME" ]]
do
    cat "$PIPE_NAME" | \
        while read line
        do
            case "$line" in
                "")
                    ;;
                "$KILL_STRING")
                    echo "sys.exit(0)"
                    rm "$PIPE_NAME"
                    break
                    ;;
                EOF)
                    break
                    ;;
                *)
                    echo "$line"
                    ;;

            esac
        done
done | $PIPED_SHELL -i -c "import sys;sys.ps1 = \"\";sys.ps2 = \"\""
