#! /usr/bin/sh

PYTHON=/bin/python3
mkfifo .pype
while [[ -a .pype ]]
do
    cat .pype | \
        while read line
        do
            case "$line" in
                "")
                    ;;
                KILL_PYPER)
                    echo "sys.exit(0)"
                    rm .pype
                    break
                    ;;
                EOF)
                    break
                    ;;
                *)
                    echo "$line"
                    ;;

            esac
        done
done | $PYTHON -i -c "import sys;sys.ps1 = \"\";sys.ps2 = \"\""
